---
# main.yml

- include_tasks: 
    file: precheck.yml
    apply:
      tags: precheck
  tags: [precheck]

- include_tasks: 
    file: nxos_upgrade.yml
    apply:
      tags: upgrade
  tags: [upgrade]
  when: ansible_network_os == 'nxos'

- include_tasks:
    file: postcheck.yml
    apply:
      tags: postcheck
  tags: [postcheck]

- include_tasks: 
    file: nxos_rollback.yml
  when: _rollback