---
# precheck

- name: Cisco NXOS get old status
  block:
  - name: get current installed OS version
    cisco.nxos.nxos_command:
      commands: show version | json
    register: _old_version
  - set_fact:
      _old_kickstart: "{{ _old_version['stdout'][0]['kickstart_ver_str'] }}"
      _old_kickstart_image: "{{ _old_version['stdout'][0]['kick_file_name'] | regex_replace('^.*:///') }}"
  - debug: 
      var: _old_kickstart_image
      verbosity: 2
  when: ansible_network_os == 'nxos'

- name: "check for later comparison: {{ update_check_command }}"
  ansible.utils.cli_parse:
    command: "{{ update_check_command }}"
    parser: 
      name: "{{ update_check_parser }}"
  register: _reference_check

- name: print reference check output
  debug:
    var: _reference_check.parsed
    verbosity: 2
  
# - name: set stat module
#   set_stats: 
#     data:
#       cachedvar: "new cache var"  
#     per_host: no