---
# main upgrade part

- name: Cisco NXOS upgrade 
  block:
  - name: check file presence on device
    cisco.nxos.nxos_command:
      commands: "dir | include {{ update_file_name }}"
    register: _filepresence
  - debug:
      var: _filepresence
  - name: get file checksum
    cisco.nxos.nxos_command:
      commands: "show file bootflash:{{ update_file_name }} {{ update_file_checksum_methode}}"
    when: update_file_checksum != "" and _filepresence.stdout[0] != ""
    register: _checksum
  - name: skip this if file not present or checksum invalid
    set_fact:
      _ready: true
    when: _filepresence.stdout[0] != "" or
       (_checksum.changed and _checksum.stdout_lines[0] == update_file_checksum)
  - debug:
      var: _ready

  - name: copy image from server 
    cisco.nxos.nxos_file_copy: 
      file_pull: true
      file_pull_protocol: "{{ update_server_protocol }}"
      file_system: "{{ update_server_filesystem }}"
      local_file: 
      remote_file: "{{update_server_directory}}{{ update_file_name }}"
      remote_scp_server: "{{ update_server_ipv4 }}"
      remote_scp_server_user: "{{ update_server_user }}"
      remote_scp_server_password: "{{ update_server_password }}"
      vrf: "{{ update_local_vrf }}"
    when: not _ready
    register: _filecopy

  - name: verify checksum of copied file 
    cisco.nxos.nxos_command:
      commands: "show file bootflash:{{ update_file_name }} {{ update_file_checksum_methode}}"
    when: _filecopy.changed and update_file_checksum != ""
    register: _checksumnew
  - debug:
      var: _checksumnew
  - name: fail if checksum of file is incorrect after copy
    fail: 
      msg: "checksum calculated: {{ _checksumnew.stdout_lines[0] }}, expected: {{ update_file_checksum }}"
    when: _filecopy.changed and update_file_checksum != "" and _checksumnew.stdout_lines[0] != update_file_checksum
  
  rescue:
  - name: delete copied file if checkum failed
    cisco.nxos.nxos_command:
      commands: 
        - command: "delete {{ update_server_filesystem }}{{ update_file_name }}"
          prompt: "Do you want to delete .*"
          answer: y

  when: inventory_hostname in groups['nxos']
